/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const {
    existsSync
} = require('fs')
const {
    join
} = require('path')

const {
    platform,
    arch
} = process

let nativeBinding = null
let loadError = null

function getPlatformPath() {
    switch (platform) {
        case 'win32':
            switch (arch) {
                case 'x64':
                    return join(__dirname, 'x64', 'file-utilities.node')
                case 'ia32':
                    return join(__dirname, 'ia32', 'file-utilities.node')
                default:
                    throw new Error(`Unsupported architecture on Windows: ${arch}`)
            }
        case 'darwin':
            switch (arch) {
                case 'x64':
                    return join(__dirname, 'darwin', 'file-utilities.node')
                case 'arm64':
                    return join(__dirname, 'darwin-arm', 'file-utilities.node')
                default:
                    throw new Error(`Unsupported architecture on macOS: ${arch}`)
            }
        default:
            throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
    }
}

try {
    const bindingPath = getPlatformPath()
    if (existsSync(bindingPath)) {
        nativeBinding = require(bindingPath)
    } else {
        throw new Error(`Native binding not found at: ${bindingPath}`)
    }
} catch (e) {
    loadError = e
}

if (!nativeBinding) {
    if (loadError) {
        throw loadError
    }
    throw new Error(`Failed to load native binding`)
}

const {
    getDirectorySizeSync: nativeGetDirectorySizeSync,
    getDirectorySizeAsync: nativeGetDirectorySizeAsync,
    detectHardlinksSync,
    detectHardlinksAsync,
    detectFilesystemSync,
    detectFilesystemAsync,
    getDirectorySizeByGlobSync,
    getDirectorySizeByGlobAsync,
    getDirectorySizeTreeSync: nativeGetDirectorySizeTreeSync,
    getDirectorySizeTreeAsync: nativeGetDirectorySizeTreeAsync,
    cancelJob
} = nativeBinding

// Job ID counter for cancellation support
let nextJobId = 1

function getNextJobId() {
    return nextJobId++
}

/**
 * Wrapper for getDirectorySizeSync that supports options-based signature
 * @param {string} path - Directory path to calculate size for
 * @param {object} [options] - Options object with optional workers and deep settings
 * @returns {object} DirectorySizeResult or DirectoryTreeResult
 */
function getDirectorySizeSync(path, options) {
    // Reject legacy numeric signature
    if (typeof options === 'number') {
        throw new Error('Numeric worker count is no longer supported. Use options object: { workers: N }')
    }

    // Handle undefined or options object
    if (options === undefined || options === null) {
        return nativeGetDirectorySizeSync(path, undefined)
    }

    if (typeof options !== 'object') {
        throw new Error('Second argument must be an options object')
    }

    // Reject AbortSignal in sync mode
    if (options.abortSignal) {
        throw new Error('AbortSignal is only supported for async operations')
    }

    // Check if deep option is requested
    if (options.deep) {
        // Validate deep options
        const deepOpts = typeof options.deep === 'boolean' ? {} : options.deep

        if (typeof options.deep === 'object' && typeof deepOpts.maxDepth !== 'number') {
            throw new Error('deep.maxDepth is required and must be a number')
        }

        const maxDepth = typeof options.deep === 'boolean' ? 3 : deepOpts.maxDepth

        if (maxDepth < 0) {
            throw new Error('deep.maxDepth must be >= 0')
        }

        // Build options for tree function
        const treeOptions = {
            maxDepth,
            workers: options.workers,
            includeRoot: deepOpts.includeRoot
        }

        return nativeGetDirectorySizeTreeSync(path, treeOptions)
    }

    // Object without deep option - pass workers in options object
    return nativeGetDirectorySizeSync(path, options.workers !== undefined ? {
        workers: options.workers
    } : undefined)
}

/**
 * Wrapper for getDirectorySizeAsync that supports options-based signature
 * @param {string} path - Directory path to calculate size for
 * @param {object} [options] - Options object with optional workers and deep settings
 * @returns {Promise<object>} Promise resolving to DirectorySizeResult or DirectoryTreeResult
 */
function getDirectorySizeAsync(path, options) {
    // Reject legacy numeric signature
    if (typeof options === 'number') {
        return Promise.reject(new Error('Numeric worker count is no longer supported. Use options object: { workers: N }'))
    }

    // Handle undefined or options object
    if (options === undefined || options === null) {
        options = {}
    }

    if (typeof options !== 'object') {
        return Promise.reject(new Error('Second argument must be an options object'))
    }

    // Handle AbortSignal
    const abortSignal = options.abortSignal
    if (abortSignal) {
        // Check if already aborted
        if (abortSignal.aborted) {
            return Promise.reject(new DOMException('Operation was aborted', 'AbortError'))
        }
    }

    const jobId = getNextJobId()
    let abortListener = null

    // Create promise that handles cancellation
    const promise = (async () => {
        try {
            // Check if deep option is requested
            if (options.deep) {
                // Validate deep options
                const deepOpts = typeof options.deep === 'boolean' ? {} : options.deep

                if (typeof options.deep === 'object' && typeof deepOpts.maxDepth !== 'number') {
                    throw new Error('deep.maxDepth is required and must be a number')
                }

                const maxDepth = typeof options.deep === 'boolean' ? 10 : deepOpts.maxDepth

                if (maxDepth < 0) {
                    throw new Error('deep.maxDepth must be >= 0')
                }

                // Build options for tree function
                const treeOptions = {
                    maxDepth,
                    workers: options.workers,
                    includeRoot: deepOpts.includeRoot
                }

                return await nativeGetDirectorySizeTreeAsync(path, treeOptions, jobId)
            }

            // Object without deep option - pass workers in options object
            return await nativeGetDirectorySizeAsync(
                path,
                options.workers !== undefined ? {
                    workers: options.workers
                } : undefined,
                jobId
            )
        } finally {
            // Clean up abort listener
            if (abortSignal && abortListener) {
                abortSignal.removeEventListener('abort', abortListener)
            }
        }
    })()

    // Attach abort listener if signal provided
    if (abortSignal) {
        abortListener = () => {
            cancelJob(jobId)
        }
        abortSignal.addEventListener('abort', abortListener)
    }

    return promise
}

/**
 * Wrapper for getDirectorySizeByGlobSync that supports options-based signature
 * @param {string} pattern - Glob pattern to match files/directories
 * @param {object} [options] - Options object with optional workers
 * @returns {object} DirectorySizeResult
 */
function getDirectorySizeByGlobSyncWrapper(pattern, options) {
    // Reject legacy numeric signature
    if (typeof options === 'number') {
        throw new Error('Numeric worker count is no longer supported. Use options object: { workers: N }')
    }

    // Handle undefined or options object
    if (options === undefined || options === null) {
        return getDirectorySizeByGlobSync(pattern, undefined)
    }

    if (typeof options !== 'object') {
        throw new Error('Second argument must be an options object')
    }

    // Pass workers in options object
    return getDirectorySizeByGlobSync(pattern, options.workers !== undefined ? {
        workers: options.workers
    } : undefined)
}

/**
 * Wrapper for getDirectorySizeByGlobAsync that supports options-based signature
 * @param {string} pattern - Glob pattern to match files/directories
 * @param {object} [options] - Options object with optional workers
 * @returns {Promise<object>} Promise resolving to DirectorySizeResult
 */
function getDirectorySizeByGlobAsyncWrapper(pattern, options) {
    // Reject legacy numeric signature
    if (typeof options === 'number') {
        return Promise.reject(new Error('Numeric worker count is no longer supported. Use options object: { workers: N }'))
    }

    // Handle undefined or options object
    if (options === undefined || options === null) {
        options = {}
    }

    if (typeof options !== 'object') {
        return Promise.reject(new Error('Second argument must be an options object'))
    }

    // Handle AbortSignal
    const abortSignal = options.abortSignal
    if (abortSignal) {
        // Check if already aborted
        if (abortSignal.aborted) {
            return Promise.reject(new DOMException('Operation was aborted', 'AbortError'))
        }
    }

    const jobId = getNextJobId()
    let abortListener = null

    // Create promise that handles cancellation
    const promise = (async () => {
        try {
            // Pass workers in options object
            return await getDirectorySizeByGlobAsync(
                pattern,
                options.workers !== undefined ? {
                    workers: options.workers
                } : undefined,
                jobId
            )
        } finally {
            // Clean up abort listener
            if (abortSignal && abortListener) {
                abortSignal.removeEventListener('abort', abortListener)
            }
        }
    })()

    // Attach abort listener if signal provided
    if (abortSignal) {
        abortListener = () => {
            cancelJob(jobId)
        }
        abortSignal.addEventListener('abort', abortListener)
    }

    return promise
}

module.exports.getDirectorySizeSync = getDirectorySizeSync
module.exports.getDirectorySizeAsync = getDirectorySizeAsync
module.exports.detectHardlinksSync = detectHardlinksSync
module.exports.detectHardlinksAsync = detectHardlinksAsync
module.exports.detectFilesystemSync = detectFilesystemSync
module.exports.detectFilesystemAsync = detectFilesystemAsync
module.exports.getDirectorySizeByGlobSync = getDirectorySizeByGlobSyncWrapper
module.exports.getDirectorySizeByGlobAsync = getDirectorySizeByGlobAsyncWrapper